//multi-dimension arrays that contain verbs, adjectives
//arrays are per alphabet character, so A verbs, B verbs, C verbs etc

//verb = action (like "lament")
//adjective = descriptive word (like "pleasant")

exports.ar_REF_verbs = [
    ["accept","ache","acknowledge","act","add","admire","admit","admonish","adopt","advise","affirm","afford","agree","ail","alert","allege","allow","allude","amuse","analyze","announce","annoy","answer","apologize","appeal","appear","applaud","appreciate","argue","arrange","arrest","arrive","articulate","ask","assert","assure","attach","attack","attempt","attend","attract","auction","avoid","avow","awake"],
    ["babble","back","bake","balance","balk","ban","bandage","bang","bar","bare","bargain","bark","barrage","barter","baste","bat","bathe","battle","bawl","be","beam","bear","beat","become","befriend","beg","begin","behave","believe","bellow","belong","bend","berate","besiege","bestow","bet","bid","bite","bleach","bleed","bless","blind","blink","blot","blow","blurt","blush","boast","bob","boil","bolt","bomb","book","bore","borrow","bounce","bow","box","brag","brake","branch","brand","break","breathe","breed","bring","broadcast","broil","bruise","brush","bubble","build","bump","burn","burnish","bury","buy","buzz"],
    ["cajole","calculate","call","camp","care","carry","carve","catch","cause","caution","challenge","change","chant","charge","chase","cheat","check","cheer","chew","chide","chip","choke","chomp","choose","chop","claim","clap","clean","clear","climb","clip","close","coach","coil","collect","color","comb","come","comfort","command","comment","communicate","compare","compete","complain","complete","concede","concentrate","concern","conclude","concur","confess","confide","confirm","connect","consent","consider","consist","contain","contend","continue","cook","copy","correct","cost","cough","count","counter","cover","covet","crack","crash","crave","crawl","criticize","croak","crochet","cross","cross-examine","crowd","crush","cry","cure","curl","curse","curve","cut","cycle"],
    ["dam","damage","dance","dare","deal","debate","decay","deceive","decide","decipher","declare","decorate","delay","delight","deliver","demand","deny","depend","describe","desert","deserve","desire","deter","develop","dial","dictate","die","dig","digress","direct","disclose","dislike","dive","divide","divorce","divulge","do","dock","dole","dote","double","doubt","drag","drain","draw","dream","dress","drill","drink","drip","drive","drone","drop","drown","dry","dump","dupe","dust","dye"],
    ["earn","eat","echo","edit","educate","elope","embarrass","emigrate","emit","emphasize","employ","empty","enchant","encode","encourage","end","enjoin","enjoy","enter","entertain","enunciate","envy","equivocate","escape","evacuate","evaporate","exaggerate","examine","excite","exclaim","excuse","exercise","exhort","exist","expand","expect","expel","explain","explode","explore","extend","extoll"],
    ["face","fade","fail","fall","falter","fasten","favor","fax","fear","feed","feel","fence","fetch","fight","file","fill","film","find","fire","fish","fit","fix","flap","flash","flee","float","flood","floss","flow","flower","fly","fold","follow","fool","force","foretell","forget","forgive","form","found","frame","freeze","fret","frighten","fry","fume"],
    ["garden","gasp","gather","gaze","gel","get","gild","give","glide","glue","gnaw","go","grab","grate","grease","greet","grill","grin","grip","groan","grow","growl","grumble","grunt","guarantee","guard","guess","guide","gurgle","gush"],
    ["hail","hammer","hand","handle","hang","happen","harass","harm","harness","hate","haunt","have","head","heal","heap","hear","heat","help","hide","highlight","hijack","hinder","hint","hiss","hit","hold","hook","hoot","hop","hope","hover","howl","hug","hum","hunt","hurry","hurt"],
    ["ice","identify","ignore","imagine","immigrate","implore","imply","impress","improve","include","increase","infect","inflate","influence","inform","infuse","inject","injure","inquire","insist","inspect","inspire","instruct","intend","interest","interfere","interject","interrupt","introduce","invent","invest","invite","iron","irritate","itch"],
    ["jab","jabber","jail","jam","jeer","jest","jog","join","joke","jolt","judge","juggle","jump"],
    ["keep","kick","kill","kiss","kneel","knit","knock","knot","know"],
    ["label","lament","land","last","laugh","lay","lead","lean","learn","leave","lecture","lend","let","level","license","lick","lie","lift","light","lighten","like","list","listen","live","load","loan","lock","long","look","loosen","lose","love","lower"],
    ["mail","maintain","make","man","manage","mar","march","mark","marry","marvel","mate","matter","mean","measure","meet","melt","memorize","mend","mention","merge","milk","mine","miss","mix","moan","molt","moor","mourn","move","mow","mug","multiply","mumble","murder","mutter"],
    ["nag","nail","name","nap","need","nest","nod","note","notice","number"],
    ["obey","object","observe","obtain","occur","offend","offer","ogle","oil","omit","open","operate","order","overflow","overrun","owe","own"],
    ["pack","pad","paddle","paint","pant","park","part","pass","paste","pat","pause","pay","peck","pedal","peel","peep","peer","peg","pelt","perform","permit","pester","pet","phone","pick","pinch","pine","place","plan","plant","play","plead","please","pledge","plow","plug","point","poke","polish","ponder","pop","possess","post","postulate","pour","practice","pray","preach","precede","predict","prefer","prepare","present","preserve","press","pretend","prevent","prick","print","proceed","proclaim","produce","profess","program","promise","propose","protect","protest","provide","pry","pull","pump","punch","puncture","punish","push","put"],
    ["question","quit","quiz","quote"],
    ["race","radiate","rain","raise","rant","rate","rave","reach","read","realize","rebuff","recall","receive","recite","recognize","recommend","record","reduce","reflect","refuse","regret","reign","reiterate","reject","rejoice","relate","relax","release","rely","remain","remember","remind","remove","repair","repeat","replace","reply","report","reprimand","reproduce","request","rescue","retire","retort","return","reveal","reverse","rhyme","ride","ring","rinse","rise","risk","roar","rob","rock","roll","rot","row","rub","ruin","rule","run","rush"],
    ["sack","sail","satisfy","save","savor","saw","say","scare","scatter","scoff","scold","scoot","scorch","scrape","scratch","scream","screech","screw","scribble","seal","search","see","sell","send","sense","separate","serve","set","settle","sever","sew","shade","shampoo","share","shave","shelter","shift","shiver","shock","shoot","shop","shout","show","shriek","shrug","shut","sigh","sign","signal","sin","sing","singe","sip","sit","skate","skateboard","sketch","ski","skip","slap","sleep","slice","slide","slip","slow","smash","smell","smile","smoke","snap","snarl","snatch","sneak","sneer","sneeze","snicker","sniff","snoop","snooze","snore","snort","snow","soak","sob","soothe","sound","sow","span","spare","spark","sparkle","speak","speculate","spell","spend","spill","spin","spoil","spot","spray","sprout","sputter","squash","squeeze","stab","stain","stammer","stamp","stand","star","stare","start","stash","state","stay","steer","step","stipulate","stir","stitch","stop","store","storm","stow","strap","stray","strengthen","stress","stretch","strip","stroke","strum","strut","stuff","stun","stunt","stutter","submerge","succeed","suffer","suggest","suit","supply","support","suppose","surmise","surprise","surround","suspect","suspend","sway","swear","swim","swing","switch","swoop","sympathize"],
    ["take","talk","tame","tap","taste","taunt","teach","tear","tease","telephone","tell","tempt","terrify","test","testify","thank","thaw","theorize","think","threaten","throw","thunder","tick","tickle","tie","time","tip","tire","toast","toss","touch","tour","tow","trace","track","trade","train","translate","transport","trap","travel","treat","tremble","trick","trickle","trim","trip","trot","trouble","trounce","trust","try","tug","tumble","turn","twist","type"],
    ["understand","undress","unfasten","unite","unlock","unpack","untie","uphold","upset","upstage","urge","use","usurp","utter"],
    ["vacuum","value","vanish","vanquish","venture","visit","voice","volunteer","vote","vouch"],
    ["wail","wait","wake","walk","wallow","wander","want","warm","warn","wash","waste","watch","water","wave","waver","wear","weave","wed","weigh","welcome","whimper","whine","whip","whirl","whisper","whistle","win","wink","wipe","wish","wobble","wonder","work","worry","wrap","wreck","wrestle","wriggle","write","writhe"],
    ["x-ray"],
    ["yawn","yell","yelp","yield","yodel"],
    ["zip","zoom"]
];

exports.ar_REF_adjectives = [
    ["adorable", "adventurous", "aggressive", "agreeable", "alert", "alive", "amused", "angry", "annoyed", "annoying", "anxious", "arrogant", "ashamed", "attractive", "average", "awful"],
    ["bad", "beautiful", "better", "bewildered", "black", "bloody", "blue", "blue-eyed", "blushing", "bored", "brainy", "brave", "breakable", "bright", "busy"],
    ["calm", "careful", "cautious", "charming", "cheerful", "clean", "clear", "clever", "cloudy", "clumsy", "colorful", "combative", "comfortable", "concerned", "condemned", "confused", "cooperative", "courageous", "crazy", "creepy", "crowded", "cruel", "curious", "cute"] 
    ["dangerous", "dark", "dead", "defeated", "defiant", "delightful", "depressed", "determined", "different", "difficult", "disgusted", "distinct", "disturbed", "dizzy", "doubtful", "drab", "dull"],
    ["eager", "easy", "elated", "elegant", "embarrassed", "enchanting", "encouraging", "energetic", "enthusiastic", "envious", "evil", "excited", "expensive", "exuberant"],
    ["fair", "faithful", "famous", "fancy", "fantastic", "fierce", "filthy", "fine", "foolish", "fragile", "frail", "frantic", "friendly", "frightened", "funny"],
    ["gentle", "gifted", "glamorous", "gleaming", "glorious", "good", "gorgeous", "graceful", "grieving", "grotesque", "grumpy"],
    ["handsome", "happy", "healthy", "helpful", "helpless", "hilarious", "homeless", "homely", "horrible", "hungry", "hurt"],
    ["ill", "important", "impossible", "inexpensive", "innocent", "inquisitive", "itchy"],
    ["jealous", "jittery", "jolly", "joyous"],
    ["kind"],
    ["lazy", "light", "lively", "lonely", "long", "lovely", "lucky"],
    ["magnificent", "misty", "modern", "motionless", "muddy", "mushy", "mysterious"],
    ["nasty", "naughty", "nervous", "nice"], 
    ["nutty"], 
    ["obedient", "obnoxious", "odd", "old-fashioned", "open", "outrageous", "outstanding"],
    ["panicky", "perfect", "plain", "pleasant", "poised", "poor", "powerful", "precious", "prickly", "proud", "putrid", "puzzled"],
    ["quaint"],
    ["real", "relieved", "repulsive", "rich"],
    ["scary", "selfish", "shiny", "shy", "silly", "sleepy", "smiling", "smoggy", "sore", "sparkling", "splendid", "spotless", "stormy", "strange", "stupid", "successful", "super"],
    ["talented", "tame", "tasty", "tender", "tense", "terrible", "thankful", "thoughtful", "thoughtless", "tired", "tough", "troubled"],
    ["ugliest", "ugly", "uninterested", "unsightly", "unusual", "upset", "uptight"],
    ["vast", "victorious", "vivacious"],
    ["wandering", "weary", "wicked", "wide-eyed", "wild", "witty", "worried", "worrisome", "wrong"],
    ["zany", "zealous"]
];

exports.ar_REF_nouns = [
    ["Ability", "Access", "Accident", "Account", "Act", "Action", "Activity", "Actor", "Ad", "Addition", "Address", "Administration", "Advantage", "Advertising", "Advice", "Affair", "Age", "Agency", "Agreement","Air", "Airport", "Alcohol", "Ambition", "Amount", "Analysis", "Analyst", "Animal", "Answer", "Anxiety", "Apartment", "Appearance", "Apple", "Application", "Appointment", "Area", "Argument", "Army", "Arrival", "Art", "Article", "Aspect", "Assignment", "Assistance", "Assistant", "Association", "Assumption", "Atmosphere", "Attempt", "Attention", "Attitude", "Audience", "Aunt", "Average", "Awareness"],
    ["Back", "Bad", "Balance", "Ball", "Bank", "Baseball", "Basis", "Basket", "Bath", "Bathroom", "Bedroom", "Beer", "Beginning", "Benefit", "Bird", "Birth", "Birthday", "Bit", "Blood", "Board", "Boat", "Body", "Bonus", "Book", "Boss", "Bottom", "Box", "Boy", "Boyfriend", "Bread", "Breath", "Brother", "Building", "Bus", "Business", "Buyer"],
    ["Cabinet", "Camera", "Cancer", "Candidate", "Capital", "Car", "Card", "Care", "Career", "Case", "Cash", "Cat", "Category", "Cause", "Celebration", "Cell", "Championship", "Chance", "Chapter", "Charity", "Cheek", "Chemistry", "Chest", "Chicken", "Child", "Childhood", "Chocolate", "Choice", "Church", "Cigarette", "City", "Class", "Classroom", "Client", "Climate", "Clothes", "Coast", "Coffee", "Collection", "College", "Combination", "Committee", "Communication", "Community", "Company", "Comparison", "Competition", "Complaint", "Computer", "Concept", "Conclusion", "Condition", "Confusion", "Connection", "Consequence", "Construction", "Contact", "Context", "Contract", "Contribution", "Control", "Conversation", "Cookie", "Country", "County", "Courage", "Course", "Cousin", "Craft", "Credit", "Criticism", "Culture", "Currency", "Customer", "Cycle"],
    ["Dad", "Data", "Database", "Date", "Day", "Dealer", "Death", "Debt", "Decision", "Definition", "Delivery", "Demand", "Department", "Departure", "Depression", "Depth", "Description", "Design", "Desk", "Development", "Device", "Diamond", "Difference", "Difficulty", "Dinner", "Direction", "Director", "Dirt", "Disaster", "Discipline", "Discussion", "Disease", "Disk", "Distribution", "Dog", "Drama", "Drawer", "Drawing", "Driver"],
    ["Ear", "Earth", "Economics", "Economy", "Editor", "Education", "Effect", "Efficiency", "Effort", "Egg", "Election", "Elevator", "Emotion", "Emphasis", "Employee", "Employer", "Employment", "End", "Energy", "Engine", "Entertainment", "Enthusiasm", "Entry", "Environment", "Equipment", "Error", "Establishment", "Estate", "Event", "Exam", "Examination", "Example", "Exchange", "Excitement", "Exercise", "Experience", "Explanation", "Expression", "Extent", "Eye"],
    ["Face", "Fact", "Failure", "Family", "Farmer", "Fat", "Feature", "Feedback", "Field", "Figure", "Film", "Finding", "Fire", "Fish", "Flight", "Focus", "Food", "Football", "Force", "Form", "Fortune", "Foundation", "Frame", "Freedom", "Friendship", "Fun", "Funeral", "Future"],
    ["Game", "Garbage", "Garden", "Gate", "Gene", "Gift", "Girl", "Girlfriend", "Goal", "Government", "Grandmother", "Grocery", "Group", "Growth", "Guest", "Guidance", "Guide", "Guitar"],
    ["Hair", "Half", "Hall", "Hand", "Hat", "Head", "Health", "Hearing", "Heart", "Heat", "Height", "Highway", "Historian", "History", "Home", "Homework", "Honey", "Hope", "Hospital", "Hotel", "House", "Housing"],
    ["Ice", "Idea", "Image", "Imagination", "Impact", "Importance", "Impression", "Improvement", "Income", "Independence", "Indication", "Industry", "Inflation", "Information", "Initiative", "Injury", "Insect", "Inside", "Inspection", "Inspector", "Instance", "Instruction", "Insurance", "Intention", "Interaction", "Interest", "Internet", "Introduction", "Investment", "Issue", "Item"],
    ["Job", "Judgment"],
    ["Key", "Kind", "King", "Knowledge"],
    ["Lab", "Ladder", "Lady", "Lake", "Language", "Law", "Leader", "Leadership", "Length", "Level", "Library", "Life", "Light", "Line", "Link", "List", "Literature", "Location", "Loss", "Love"],
    ["Machine", "Magazine", "Maintenance", "Mall", "Man", "Management", "Manager", "Manufacturer", "Map", "Market", "Marketing", "Marriage", "Material", "Math", "Matter", "Meal", "Meaning", "Measurement", "Meat", "Media", "Medicine", "Medium", "Member", "Membership", "Memory", "Menu", "Message", "Metal", "Method", "Midnight", "Mind", "Mixture", "Mode", "Model", "Mom", "Moment", "Money", "Month", "Mood", "Morning", "Mouse", "Movie", "Mud", "Music"],
    ["Name", "Nation", "Nature", "Negotiation", "Network", "News", "Newspaper", "Night", "Note", "Nothing", "Number"],
    ["Object", "Obligation", "Office", "Oil", "Operation", "Opinion", "Opportunity", "Orange", "Order", "Organization", "Outcome", "Outside", "Oven", "Owner"],
    ["Page", "Paint", "Painting", "Paper", "Part", "Passenger", "Passion", "Patience", "Payment", "Penalty", "People", "Percentage", "Perception", "Performance", "Period", "Permission", "Person", "Personality", "Perspective", "Philosophy", "Phone", "Photo", "Physics", "Piano", "Picture", "Pie", "Piece", "Pizza", "Place", "Plan", "Platform", "Player", "Poem", "Poet", "Poetry", "Point", "Police", "Policy", "Politics", "Pollution", "Population", "Position", "Possession", "Possibility", "Post", "Pot", "Potato", "Power", "Practice", "Preference", "Preparation", "Presence", "Presentation", "President", "Pressure", "Price", "Priority", "Problem", "Procedure", "Process", "Product", "Profession", "Professor", "Profit", "Program", "Promotion", "Property", "Proposal", "Protection", "Psychology", "Purpose"],
    ["Quality", "Quantity", "Queen", "Question"],
    ["Radio", "Range", "Rate", "Ratio", "Reaction", "Reality", "Reason", "Reception", "Recipe", "Recognition", "Recommendation", "Record", "Recording", "Reflection", "Refrigerator", "Region", "Relation", "Relationship", "Replacement", "Republic", "Reputation", "Requirement", "Research", "Resolution", "Resource", "Response", "Responsibility", "Restaurant", "Result", "Revenue", "Review", "Revolution", "Risk", "River", "Road", "Rock", "Role", "Room", "Rule"],
    ["Safety", "Salad", "Salt", "Sample", "Satisfaction", "Scale", "Scene", "School", "Science", "Screen", "Secretary", "Section", "Sector", "Security", "Selection", "Sense", "Series", "Service", "Session", "Setting", "Shape", "Share", "Shirt", "Side", "Sign", "Signature", "Significance", "Singer", "Sir", "Sister", "Site", "Situation", "Size", "Skill", "Society", "Software", "Soil", "Solution", "Son", "Song", "Sound", "Soup", "Source", "Space", "Speaker", "Speech", "Sport", "Square", "Standard", "Star", "State", "Statement", "Steak", "Step", "Stock", "Storage", "Store", "Story", "Stranger", "Strategy", "Stress", "Structure", "Student", "Studio", "Study", "Style", "Subject", "Success", "Suggestion", "Sun", "Supermarket", "Surgery", "Sympathy", "System"],
    ["Table", "Tale", "Task", "Tax", "Tea", "Teacher", "Technology", "Television", "Temperature", "Tennis", "Tension", "Term", "Test", "Thanks", "Theory", "Thing", "Thought", "Throat", "Time", "Tongue", "Tool", "Tooth", "Top", "Topic", "Town", "Trade", "Tradition", "Trainer", "Training", "Transportation", "Truth", "Two", "Type"],
    ["Uncle", "Understanding", "Union", "Unit", "University", "User"],
    ["Value", "Variation", "Variety", "Vehicle", "Version", "Video", "View", "Village", "Virus", "Voice", "Volume"],
    ["War", "Warning", "Water", "Way", "Weakness", "Wealth", "Weather", "Web", "Wedding", "Week", "While", "Wife", "Wind", "Winner", "Woman", "Wood", "Word", "Work", "Worker", "World", "Writer", "Writing"],
    ["Xylophone"],
    ["Year", "Youth"],
    ["Zone"]
];